version: "3.9"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  chat:
    build: .
    ports:
      - "8000:3000"
    depends_on:
      - mongodb
volumes:
  dbdata6:
